version: '3.8'

services:

  db:
    image: postgres
    container_name: best_travel
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_USER=mateo
      - POSTGRES_PASSWORD=1297
      - POSTGRES_DB=best_travel

  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - db